services:

  mongodb:
    build: database
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - credit-network

  credit:
    build:
      target: prod
    environment:  # TODO?
      - PORT=8080
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
      - DB_NAME="creditDB"
      - DB_COLLECTION_NAME="credit"
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - credit-network

volumes:
  dbdata6:

networks:
  credit-network:
    driver: bridge
