services:

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - credit-network

  credit:
    build: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - credit-network
    develop:
      watch:
        - action: sync
          path: src
          target: /app/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json

volumes:
  dbdata6:

networks:
  credit-network:
    driver: bridge
