openapi: 3.0.0
info:
  title: Credit Service API
  description: API pour gérer le solde des crédits et l'historique des transactions pour Manamon.
  version: 1.0.0
servers:
  - url: http://credit:8080
    description: Serveur de production
  - url: http://localhost:8080
    description: Serveur de développement

paths:
  /credit/{userId}:
    get:
      summary: Obtenir le solde de crédits d'un utilisateur
      description: Retourne le solde de crédits pour un utilisateur spécifique.
      parameters:
        - name: userId
          in: path
          required: true
          description: Identifiant de l'utilisateur
          schema:
            type: string
      responses:
        200:
          description: Solde de crédits récupéré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    example: "12345"
                  balance:
                    type: number
                    format: float
                    example: 100.0
        500:
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Une erreur est survenue"

  /credit/update:
    post:
      summary: Mettre à jour le solde de crédit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: "12345"
                transactionType:
                  type: string
                  enum: [purchase, gain, sale]
                  example: "purchase"
                amount:
                  type: number
                  format: float
                  example: 50.0
      responses:
        200:
          description: Solde de crédit mis à jour avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    example: "12345"
                  newBalance:
                    type: number
                    format: float
                    example: 120.0
        500:
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Une erreur est survenue"

  /credit/{userId}/transactions:
    get:
      summary: Récupérer l'historique des transactions
      description: Retourne l'historique complet des transactions pour un utilisateur spécifique.
      parameters:
        - name: userId
          in: path
          required: true
          description: Identifiant de l'utilisateur
          schema:
            type: string
      responses:
        200:
          description: Historique des transactions récupéré avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionId:
                      type: string
                      example: "txn-001"
                    date:
                      type: string
                      format: date-time
                      example: "2025-01-17T12:34:56Z"
                    transactionType:
                      type: string
                      enum: [purchase, gain, sale]
                      example: "purchase"
                    amount:
                      type: number
                      format: float
                      example: 50.0
        500:
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Une erreur est survenue"